version: '3.9'

services:
  # сервис Scrapy
  app:
    build: .
    image: scrapy
    env_file:
      - .env
    volumes:
      - ./src:/src
      - ./docs:/docs
      - ./poetry.lock:/poetry.lock
    working_dir: /src/
